version: 0.2
artifacts:
    base-directory: public
    files:
        - '**/*'
cache:
    paths:
        - '.cache/*'
        - 'public/*'
phases:
    install:
        commands:
            - touch .npmignore
            - npm install -g gatsby
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build
            - npm run deploy
            - aws cloudfront create-invalidation --distribution-id $CLOUD_DIST_ID --paths "/*"